import type { Metadata } from 'next'
import Link from 'next/link'
import Nav from '@/components/layout/Nav'
import Footer from '@/components/layout/Footer'

export const metadata: Metadata = {
  title: 'Tools',
}

const tools = [
  {
    title: 'Bracket Generator',
    description: 'Create tournament brackets for any number of players. Single elimination, double elimination, or round robin.',
    href: '/tools/brackets',
    icon: (
      <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 6h4v4H4zM4 14h4v4H4zM16 10h4v4h-4zM10 8h6M10 16h6" />
      </svg>
    ),
  },
  {
    title: 'AI Drill Planner',
    description: 'Get personalized drill plans generated by AI based on your skill level and areas for improvement.',
    href: '/tools/drills',
    icon: (
      <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
      </svg>
    ),
  },
  {
    title: 'ELO Calculator',
    description: 'Calculate expected outcomes and rating changes for pickleball matches using the ELO rating system.',
    href: '/tools/elo',
    icon: (
      <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 7h6m0 10v-3m-3 3h.01M9 17h.01M9 14h.01M12 14h.01M15 11h.01M12 11h.01M9 11h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
      </svg>
    ),
  },
  {
    title: 'String Tension Guide',
    description: 'Find the ideal string tension for your paddle based on playing style, temperature, and preferences.',
    href: '/tools/elo',
    icon: (
      <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4" />
      </svg>
    ),
  },
]

export default function ToolsPage() {
  return (
    <>
      <Nav />
      <main className="max-w-site mx-auto px-5 py-6">
        <h1 className="font-condensed text-3xl font-bold uppercase border-b-2 border-ink pb-2.5">
          Tools
        </h1>
        <p className="text-sm text-ink4 mt-2 mb-6">
          Free pickleball tools to help you play, organize, and improve.
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {tools.map((tool) => (
            <Link
              key={tool.title}
              href={tool.href}
              className="group flex gap-4 p-6 border border-border rounded-lg hover:shadow-md hover:border-blue/30 transition-all duration-fast bg-white"
            >
              <div className="w-14 h-14 shrink-0 bg-bg2 rounded-lg flex items-center justify-center text-ink3 group-hover:bg-blue/10 group-hover:text-blue transition-colors">
                {tool.icon}
              </div>
              <div>
                <h3 className="font-condensed text-lg font-bold uppercase group-hover:text-blue transition-colors">
                  {tool.title}
                </h3>
                <p className="text-sm text-ink4 mt-1 leading-relaxed">{tool.description}</p>
              </div>
            </Link>
          ))}
        </div>
      </main>
      <Footer />
    </>
  )
}
